AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  recomv2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 20
      Role: 'arn:aws:iam::714213135128:role/lambda_witf_recommender'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /recom_v2
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /recom_v2
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - sg-08351c449cba1e0cc
        SubnetIds:
          - subnet-01a999dcbaec09d01
